name: 'Bump Release Please Version | Pipeline'

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'The release tag to bump the releases to'
        required: false
        default: '1.0.0'
        type: string
      modpack:
        description: 'Path to the modpack directory'
        required: false
        default: 'main'
        type: string
  workflow_call:
    inputs:
      release-tag:
        description: 'The release tag to bump the releases to'
        required: false
        default: '1.0.0'
        type: string
      
jobs:
  set-version:
    runs-on: ubuntu-latest

    name: Update Version

    permissions:
      contents: write

    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v4

      - name: Get current branch
        id: branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Set the New Version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--allow-empty'
          skip_dirty_check: true
          push_options: --force
          commit_message: |
            chore(${{ steps.branch.outputs.branch }}): release ${{ inputs.release-tag }}
            Release-As: ${{ inputs.release-tag }}}
